- hosts: all
  remote_user: root
  vars_files:
    - var.yaml

  tasks:
    - name: 关闭firewalld
      service: name=firewalld state=stopped enabled=no

    - name: 关闭selinux
      lineinfile:
        dest: /etc/selinux/config
        regexp: "^SELINUX="
        line: "SELINUX=disabled"

    - name: 关闭swap
      lineinfile:
        dest: /etc/fstab
        regexp: ".*swap"
        line: ""

    - name: 即时生效
      shell: setenforce 0; swapoff -a

