apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx 
  strategy:
    type: Recreate
  replicas: 4
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:li
          name: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
