apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx 
  strategy:
    type: Recreate
  replicas: 3
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:li
          name: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volume
          hostPath:
            path: /root/html
            type: Directory
