apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
  labels:
    app: li
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.20.173
    path: "/nfs"
